In [1]:
import numpy as np

In [2]:
# check the numpy version
np.__version__

'1.19.2'

numpy 배열의 모든 요소가 같은 타입이어야 함 <br>
numpy 배열은 명시적으로 다차원이 가능함

In [13]:
# array
# np.array([1,4,2,5,3])

# use list comprehension initialize to multi dimension array 
np.array([range(i, i+3) for i in [1,8,10]])

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [10, 11, 12]])

### 처음부터 배열 만들기
규모가 큰 배열의 경우에 numpy에 내장된 루틴을 사용해 처음부터 배열을 생성하는 것이 더 효율적임

In [33]:
# 0으로 채워진 10의 정수 배열 만들기 
np.zeros(10,dtype=int)

# 1로 채워진 3*5 부동소수점 배열 만들기 
np.full((3,5), 1, dtype=float)

# 선형 수열로 채운 배열 만들기(0~20까지 2식 더한 배열)
np.arange(2,20,2)

# 0과 2 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기 
np.linspace(0,2,5)

# 균등하게 분포된 3*3 배열 만들기(0~1(고정) 난수)
np.random.random((3,3))

# 정규분포 m=2, sd = 0.5 의 난수로 채운 3*3배열
np.random.normal(2,0.5,(3,3))

# 1~20 구간의 임의의 정수로 채운 4*4 배열 만들기 
np.random.randint(1,20,(4,4))

# 2*2 unit matrix
np.eye(2)

# 다섯 정수를 가지는 초기화되지 않은 배열 만들기
# 같은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움
np.empty(5)

array([0. , 0.5, 1. , 1.5, 2. ])

### numpy 배열의 기초
배열 속성 지정: 배열의 크기, 모양, 메모리 소비량, 데이터 타입을 결정한다.<br>
배열 인덱싱: 개별 배열 요솟값을 가져오고 설정 <br>
배열 슬라이싱: 큰배열 내에 있는 작은 하위 배열을 가져오고 설정 <br>
배열 재구조화: 해당 배열의 형상을 변경한다. <br>
배열 결합 및 분할: 여러 배열을 하나로 결합하고 하나의 배열을 여러 개로 분할한다.

In [36]:
# 배열 속성 지정 
np.random.seed(48) # 재현을 위한 시드값 지정
x1 = np.random.randint(10,size=6) # 1-dim
x2 = np.random.randint(10,size=(3,4)) # 2-dim
x3 = np.random.randint(10,size=(3,4,5)) # 3-dim
x3

array([[[2, 5, 9, 2, 6],
        [2, 1, 5, 6, 0],
        [5, 2, 6, 6, 5],
        [6, 2, 2, 5, 4]],

       [[7, 3, 2, 0, 3],
        [3, 6, 0, 2, 1],
        [6, 9, 3, 9, 1],
        [7, 4, 2, 1, 6]],

       [[3, 5, 0, 7, 4],
        [2, 1, 9, 3, 0],
        [3, 0, 7, 4, 0],
        [3, 3, 1, 0, 6]]])

In [ ]:
# 배열 인덱싱: 단일 요소 접근
